blank_issues_enabled: false
contact_links:
  - name: 📚 Development Documentation
    url: https://github.com/GeorgeIoak/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Technical information for developers working on the website
  - name: 🆘 Urgent Technical Issues
    url: mailto:admin@mergington.edu
    about: For urgent technical problems that prevent website access, contact IT directly